version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: twh-dev
    volumes:
      - ./packages/database/data:/var/lib/postgresql/data:rw

  app:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      - PG_CONNECTION_STRING=postgresql://postgres:password@db:5432/twh-dev

  db-prod:
    image: postgres
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: twh-dev
    volumes:
      - ./db-dumps:/home:rw

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080