version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: twh-dev
    volumes:
      - ./packages/database/data:/var/lib/postgresql/data:rw
    networks:
      - internal

  app:
    build: .
    restart: always
    # ports:
    #   - "80:5000"
    depends_on:
      - db
    environment:
      - PG_CONNECTION_STRING=postgresql://postgres:password@db:5432/twh-dev
    labels:
      - "traefik.http.routers.api.rule=Host(`api.twitter-writes-hamlet.com`)"
      - "traefik.http.routers.api.tls.certresolver=le"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.docker.network=traefik-external"
    networks:
      - internal
      - traefik-external

networks:
  traefik-external:
    external: true
  internal:
    external: false